# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ec31fe21e534c4c8f6d3383b675b99aaa35af19b1d0c2ca84a8cbed70448bfa2de4cdb547e0aaab569c526cc795ff5240914393ebd193fce675049c64686fb5

test:
  secret_key_base: d59d278372db66a90403de295a2b5929985592e273a963b547b2b5a9bd5000881fa41beed8de9b6986b587e8834616a4ef14f1a7a84d9f8bf13e1a704eba8b54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
